export const mockCourses = [
    {
        id: '1',
        name: 'Real Club de Golf El Prat',
        location: 'Barcelona, España',
        image_url: 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?q=80&w=800&auto=format&fit=crop', // Man golfing (Generic/Safe)
        rating: 4.5,
        holes: 45,
        par: 72,
        amenities: ['Driving Range', 'Pro Shop', 'Restaurante', 'Piscina'],
        lat: 41.5636,
        lng: 2.0359,
        booking_url: 'https://www.realclubdegolfelprat.com/reservas',
        address: 'Plans de Bonvilar, 17, 08227 Terrassa, Barcelona'
    },
    {
        id: '2',
        name: 'Golf Santander',
        location: 'Madrid, España',
        image_url: 'https://images.unsplash.com/photo-1622396481328-9b1b78cdd9f3?q=80&w=800&auto=format&fit=crop', // Bunker/Green generic
        rating: 4.8,
        holes: 18,
        par: 72,
        amenities: ['Driving Range', 'Escuela de Golf', 'Restaurante'],
        lat: 40.3951,
        lng: -3.8757,
        booking_url: 'https://www.golfsantander.es/reservas',
        address: 'Ciudad Financiera Banco Santander, 28660 Boadilla del Monte, Madrid'
    },
    {
        id: '3',
        name: 'Centro Nacional de Golf',
        location: 'Madrid, España',
        image_url: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?q=80&w=800&auto=format&fit=crop', // Scenic green generic
        rating: 4.3,
        holes: 18,
        par: 72,
        amenities: ['Driving Range', 'Escuela de Excelencia', 'Gourmet'],
        lat: 40.5050,
        lng: -3.7250,
        booking_url: 'https://centronacionalgolf.com/reservas/',
        address: 'Calle Arroyo del Monte, 5, 28035 Madrid'
    },
    {
        id: '4',
        name: 'Club de Campo Villa de Madrid',
        location: 'Madrid, España',
        image_url: 'https://images.unsplash.com/photo-1593111774240-d529f12db490?q=80&w=800&auto=format&fit=crop', // Fairway generic
        rating: 4.7,
        holes: 36,
        par: 71,
        amenities: ['Piscina', 'Tenis', 'Hípica', 'Restaurante'],
        lat: 40.4414,
        lng: -3.7547,
        booking_url: 'https://www.ccvm.es/deportes/golf/reservas',
        address: 'Ctra. de Castilla, km 2, 28040 Madrid'
    },
    {
        id: '5',
        name: 'Real Club de la Puerta de Hierro',
        location: 'Madrid, España',
        image_url: 'https://images.unsplash.com/photo-1600607686527-6fb886090705?q=80&w=800&auto=format&fit=crop', // Aerial view generic
        rating: 4.9,
        holes: 36,
        par: 72,
        amenities: ['Exclusivo', 'Piscina', 'Tenis', 'Privado'],
        lat: 40.4578,
        lng: -3.7539,
        booking_url: 'https://www.rcph.es/',
        address: 'Av. de Miraflores, s/n, 28035 Madrid'
    },
    {
        id: '6',
        name: 'Golf Park',
        location: 'Alcobendas, Madrid',
        image_url: 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?q=80&w=800&auto=format&fit=crop',
        rating: 4.0,
        holes: 9,
        par: 27,
        amenities: ['Pitch & Putt', 'Padel', 'Driving Range'],
        lat: 40.5286,
        lng: -3.6493,
        booking_url: 'https://www.golfpark.es/reservas',
        address: 'Av. de Europa, 2, 28108 Alcobendas, Madrid'
    },
    {
        id: '7',
        name: 'Golf La Moraleja',
        location: 'Alcobendas, Madrid',
        image_url: 'https://images.unsplash.com/photo-1600607686527-6fb886090705?q=80&w=800&auto=format&fit=crop',
        rating: 4.8,
        holes: 72,
        par: 72,
        amenities: ['4 Campos', 'Spa', 'Tenis', 'Gimnasio'],
        lat: 40.5192,
        lng: -3.6417,
        booking_url: 'https://www.golflamoraleja.com/',
        address: 'Paseo de la Marquesa Viuda de Aldama, 50, 28109 Alcobendas, Madrid'
    },
    {
        id: '8',
        name: 'Real Sociedad Hípica Española Club de Campo',
        location: 'San Sebastián de los Reyes, Madrid',
        image_url: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?q=80&w=800&auto=format&fit=crop',
        rating: 4.6,
        holes: 36,
        par: 72,
        amenities: ['Hípica', 'Tenis', 'Piscina', 'Familiar'],
        lat: 40.6078,
        lng: -3.5867,
        booking_url: 'https://www.rshecc.es/',
        address: 'Ctra. de Burgos, km 26,400, 28709 San Sebastián de los Reyes, Madrid'
    },
    {
        id: '9',
        name: 'Club de Golf Retamares',
        location: 'Alalpardo, Madrid',
        image_url: 'https://images.unsplash.com/photo-1622396481328-9b1b78cdd9f3?q=80&w=800&auto=format&fit=crop',
        rating: 4.4,
        holes: 18,
        par: 72,
        amenities: ['Hotel', 'Eventos', 'Tenis'],
        lat: 40.6186,
        lng: -3.5042,
        booking_url: 'https://www.golfretamares.com/reservas',
        address: 'Calle Croacia, s/n, 28130 Alalpardo, Madrid'
    },
    {
        id: '10',
        name: 'El Encín Golf Hotel',
        location: 'Alcalá de Henares, Madrid',
        image_url: 'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?q=80&w=800&auto=format&fit=crop',
        rating: 4.5,
        holes: 18,
        par: 72,
        amenities: ['Hotel', 'Restaurante', 'Top Tracer'],
        lat: 40.5292,
        lng: -3.3333,
        booking_url: 'https://www.encingolf.com/reservas',
        address: 'Autovía A-2, Km 35, 600, 28805 Alcalá de Henares, Madrid'
    },
    {
        id: '11',
        name: 'Golf Negralejo',
        location: 'Rivas-Vaciamadrid, Madrid',
        image_url: 'https://images.unsplash.com/photo-1593111774240-d529f12db490?q=80&w=800&auto=format&fit=crop',
        rating: 4.1,
        holes: 18,
        par: 72,
        amenities: ['Pitch & Putt', 'Escuela', 'Restaurante'],
        lat: 40.4078,
        lng: -3.5161,
        booking_url: 'https://www.golfnegralejo.com/',
        address: 'Ctra. San Fernando a Mejorada, km 2.5, 28522 Rivas-Vaciamadrid'
    }
];
