export const mockRounds = [
    {
        id: '1',
        date: '2023-10-15',
        courseName: 'Real Club de Golf El Prat',
        score: 82,
        par: 72,
        stableford: 36,
        fairways: 8,
        greens: 10,
        putts: 32,
    },
    {
        id: '2',
        date: '2023-10-22',
        courseName: 'Golf Santander',
        score: 85,
        par: 72,
        stableford: 33,
        fairways: 6,
        greens: 8,
        putts: 34,
    },
    {
        id: '3',
        date: '2023-11-05',
        courseName: 'Valderrama Golf Club',
        score: 88,
        par: 71,
        stableford: 30,
        fairways: 5,
        greens: 6,
        putts: 35,
    },
    {
        id: '4',
        date: '2023-11-12',
        courseName: 'Club de Campo Villa de Madrid',
        score: 79,
        par: 71,
        stableford: 39,
        fairways: 10,
        greens: 12,
        putts: 30,
    },
];

export const statsSummary = {
    handicap: 12.4,
    averageScore: 83.5,
    bestScore: 79,
    roundsPlayed: 24,
    golfRating: 7.8,
};
